const nicaragua = {
  Boaco: [
    "Boaco",
    "Camoapa",
    "San José de los Remates",
    "San Lorenzo",
    "Santa Lucía",
    "Teustepe",
  ],
  Carazo: [
    "Diriamba",
    "Dolores",
    "El Rosario",
    "Jinotepe",
    "La Conquista",
    "La Paz de Carazo",
    "San Marcos",
    "Santa Teresa",
  ],
  Chinandega: [
    "Chinandega",
    "El Realejo",
    "El Viejo",
    "Chichigalpa",
    "Corinto",
    "Puerto Morazán",
    "San Pedro del Norte",
    "San Francisco del Norte",
    "Posoltega",
    "Chichigalpa",
    "La Libertad",
    "Somotillo",
    "San Juan de Cinco Pinos",
    "San Antonio del Norte",
    "San José de los Remates",
  ],
  Chontales: [
    "Juigalpa",
    "Acoyapa",
    "Comalapa",
    "El Coral",
    "El Rama",
    "La Libertad",
    "La Cruz de Río Grande",
    "San Esteban",
    "San Pedro de Lóvago",
    "San Sebastián de Yalí",
    "Santa María de Pantasma",
    "Wiwi",
    "La Concordia",
    "La Dalia",
    "La Trinidad",
  ],
  Estelí: [
    "Estelí",
    "Condega",
    "La Trinidad",
    "San Juan de Limay",
    "San Nicolás",
    "Pueblo Nuevo",
    "La Concordia",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
  ],
  Granada: [
    "Granada",
    "Diriá",
    "Diriomo",
    "Nandaime",
    "San Juan de Oriente",
    "San Jorge",
    "San Francisco",
    "San Juan del Sur",
    "La Concepción",
    "La Paz",
    "La Concepción",
    "La Concepción",
    "La Concepción",
    "La Concepción",
  ],
  Jinotega: [
    "Jinotega",
    "El Cuá",
    "La Concordia",
    "San José de Bocay",
    "San Rafael del Norte",
    "San Sebastián de Yalí",
    "Santa María de Pantasma",
    "Wiwilí de Jinotega",
  ],
  León: [
    "León",
    "El Sauce",
    "La Paz Centro",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
  ],
  Madriz: [
    "Somoto",
    "San Juan de Río Coco",
    "San Lucas",
    "San José de Cusmapa",
    "San Nicolás",
    "Telpaneca",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
  ],
  Managua: [
    "Managua",
    "El Crucero",
    "La Concepción",
    "La Paz Centro",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
  ],
  Masaya: [
    "Masaya",
    "Nandasmo",
    "Nindirí",
    "Tisma",
    "Masatepe",
    "La Concepción",
    "La Paz Centro",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
  ],
  Matagalpa: [
    "Matagalpa",
    "Jinotega",
    "La Concordia",
    "San José de Bocay",
    "San Rafael del Norte",
    "San Sebastián de Yalí",
    "Santa María de Pantasma",
    "Wiwilí de Jinotega",
  ],
  "Nueva Segovia": [
    "Ocotal",
    "El Jícaro",
    "Dipilto",
    "Jalapa",
    "Murra",
    "Macuelizo",
    "San Fernando",
    "San Juan de Río Coco",
    "San Lucas",
    "San Nicolás",
    "Telpaneca",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
  ],
  Rivas: [
    "Rivas",
    "San Jorge",
    "San Juan del Sur",
    "Tola",
    "La Concepción",
    "La Paz Centro",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
    "La Paz de Carazo",
  ],
  "Río San Juan": [
    "San Carlos",
    "El Castillo",
    "San Miguelito",
    "La Cruz de Río Grande",
    "La Libertad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
  ],
  "Atlántico Norte": [
    "Bilwi",
    "Waspam",
    "Puerto Cabezas",
    "Rosita",
    "Siuna",
    "Bonanza",
    "Mulukukú",
    "La Ceiba",
    "La Cruz de Río Grande",
    "La Libertad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
  ],
  "Atlántico Sur": [
    "Bluefields",
    "Corn Island",
    "La Cruz de Río Grande",
    "La Libertad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
    "La Trinidad",
    "La Dalia",
  ],
}

export default nicaragua
